### ISSUE TITLE
Hide time tooltip for never logged in user cards

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#12145]
**Describe the bug**

The tooltip tip show on hover for the never logged in user is wrong and not relevant

**To Reproduce**

1. Go to any facility
2. go to users and hover on never logged in user
3. see the error

**Expected behavior**

Hide the time tooltip for never logged in user card

**Screenshots**

![Image](https://github.com/user-attachments/assets/55e28765-8897-45ed-a364-0449e5b21f1d)

---

### Instructions for Requesting Assignment:

To request assignment, please clearly outline your solution and timeline by commenting on the issue using the format below:

**Describe your solution clearly:**
Provide a detailed explanation of your proposed solution, including your approach, key implementation steps, and relevant examples or references. Mention any dependencies, assumptions, or risks you foresee that might affect your timeline or implementation.

**Expected Timeline:**
- End date: [Expected submission date of a completed Pull Request]

**Additional Context:**
Include any other relevant context, links, screenshots, or resources that support your proposed solution.

> 🚨 Your assignment may be unassigned if there is no activity or progress within the stated timeline unless communicated clearly and agreed upon.

**Comment by karanziie1990** [comment]
Hey @nihal467 can I take up this issue..??

ETA: Tomorrow (29/04/2025)

**Comment by Spandan-Mishra** [comment]
@nihal467 can i work on this issue?
ETA: Today
Approach: Add a check for never logged in user, conditionally rendering the tooltip

**Comment by ashwinpraveengo** [comment]
Hey @nihal467 
Can I work on this issue ?
ETA:EOD

My Spoach:
- Add a condition to check the never logged in status for displaying the time tool tip

**Comment by gobardan1707** [comment]
@nihal467 @Jacobjeevan i have solved this issue, can you please assign me this issue to raise the pr 

solution : what i have done is 
- added this logic `  const tooltipTitle = user.last_login ? new Date(user.last_login).toLocaleString() : ""; `
- changed the title to tooltiptitle 

https://github.com/user-attachments/assets/5805797b-b2ae-4dae-b955-a04f5a2ad478

END DATE : immediatly as you assign

**Comment by Srayash** [comment]
hey @nihal467, I think this issue has been resolved.

**Comment by gobardan1707** [comment]
> hey [@nihal467](https://github.com/nihal467), I think this issue has been resolved.
the issue has not resolved it is still showing for the never logged in users 

https://github.com/user-attachments/assets/731b9d92-2b45-4444-bb0c-2b8e2ae56cd2

**Comment by gobardan1707** [comment]
> hey [@nihal467](https://github.com/nihal467), I think this issue has been resolved.

the issue has not resolved it is still showing for not logged in users 

![Image](https://github.com/user-attachments/assets/88862dbc-9ef8-4109-a6a9-0fe8c6c28a34)

**Comment by Srayash** [comment]
> the issue has not resolved it is still showing for not logged in users
> 
> ![Image](https://github.com/user-attachments/assets/88862dbc-9ef8-4109-a6a9-0fe8c6c28a34)


thanks for the clarification @gobardan1707 and sorry for the confusion, may be a browser issue on my end.

**Comment by gigincg** [comment]
@gobardan1707  Assigned

**Comment by gobardan1707** [comment]
@gigincg done .
