### ISSUE TITLE
Add Validation to Bed Assignment

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3018]
Currently, more than one patient can be admitted to the same bed.
Eg:
<img width="916" alt="Screenshot 2022-07-06 at 11 56 35 AM" src="https://user-images.githubusercontent.com/67050716/177483317-d8654cc1-7da7-4507-9878-407861461c36.png">

https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patients

When assigning bed either on 

consultation page (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/76742faa-30dd-4eb9-9649-fe718f947ec0/consultation/2ad89b7c-7bff-4035-a3c6-36d53551a8f0/update) / 

Switch bed   section (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/76742faa-30dd-4eb9-9649-fe718f947ec0/consultation/2ad89b7c-7bff-4035-a3c6-36d53551a8f0)

The user must be allowed to only assign the beds that are not occupied at that point in time.

**Comment by aeswibon** [comment]
Backend issue [coronasafe/care#854](https://github.com/coronasafe/care/pull/854)

**Comment by aparnacoronasafe** [comment]
The backend issue is resolved by @vigneshhari 

@cp-Coder Please close the issue if there is nothing more to do here.

**Comment by aeswibon** [comment]
This issue is still unresolved

https://user-images.githubusercontent.com/77210185/177998180-4aa00f95-b3ee-4f73-b268-aa9e4c890308.mp4

**Comment by aeswibon** [comment]
The issue has been fixed
